FROM python:3.12-rc-alpine as python_build
#Переносим исходники в контейнер
WORKDIR /app
COPY ./src/requirements.txt .
#Ставим зависимости
RUN apk add alpine-conf
RUN setup-apkrepos -cf
RUN apk update
RUN apk add "libssl3>3.3.3" libpq-dev rust cargo "librdkafka-dev>2.8.0" --virtual build-deps \
    && pip install -r requirements.txt \
    && apk del build-deps
#Добавляем зависимости времени выполнения
RUN apk add libpq librdkafka>2.8.0
COPY ./src .
#Добавляем точку входа в контейнер
ENTRYPOINT ["python", "main.py"]