FROM python:3.12-rc-alpine as python_build
#Переносим исходники в контейнер
WORKDIR /app
COPY ./src/requirements.txt .
#Ставим зависимости
RUN apk add libpq-dev rust cargo --virtual build-deps \
    && pip install -r requirements.txt \
    && apk del build-deps
#Добавляем зависимости времени выполнения
RUN apk add libpq
COPY ./src .
#Добавляем точку входа в контейнер
ENTRYPOINT ["fastapi", "run", "main.py", "--port", "80"]