name: Type check

on: [push]

jobs:
  mypy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    name: MyPy check...
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        pip install -r src/task_service/src/requirements.txt
        pip install -r src/detection_model_service/src/requirements.txt
    - name: Analysing the code with mypy
      run: |
        mypy --disallow-untyped-defs --namespace-packages --explicit-package-bases src
